require "date"
require "pry"
require "net/http"
require "json"
require "time"

require "./lib/Flatiron_Project1_CLI_200818/cli"
require "./lib/Flatiron_Project1_CLI_200818/earth_weather"
require "./lib/Flatiron_Project1_CLI_200818/martian_weather"
require "./lib/Flatiron_Project1_CLI_200818/latlong_creator"
